config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  resources :articles do 
  	collection do
  		post "active" 
  	end
  end
  resources :comments do
  	collection do 
  		get "popup"
  	end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  	has_many :comments , dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   	has_many :articles, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles=Article.all
	end

	# def new
	# 	#debugger
	# 	@user = User.find(params[:id])
	# end

	def create
		
	  	# @user=current_User.find(params[:article][:user_id])
	  	@article=current_user.articles.create(article_params)
	  	redirect_to root_path

  end

  def show
   @article = Article.find(params[:id])
   @comment = @article.comments.new
   @comments = @article.comments.all
  end
  	def edit
  		
  		@article= Article.find(params[:id])
  	end

  	def update
  		@article= Article.find(params[:id])
  		@article.update(article_params)
  		redirect_to root_path

  	end

  	def active
  		@article= Article.find(params[:id])
  		if (@article.active == false)
  			@article.update(active: true)
  		end
  		redirect_to root_path

  	end

  	

  	def destroy
  		@article=Article.find(params[:id])
  		@article.delete
  		redirect_to root_path
  	end

  private
  def article_params
  	params.require(:article).permit(:title,:description,:created_by,:active)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@article=Article.find(params[:id])
	end
  def create
     @article = Article.find(params[:comment][:article_id])
     @comment = @article.comments.create(comment_params)
     @comments = @article.comments
      respond_to do |format|
      format.js
     # redirect_to blog_path(id:@blog.id)
   end
  end

  def popup
    
  end

  def show
  @comment =Comment.find(params[:id])
  end

  private

	def comment_params
   params.require(:comment).permit(:user_id,:article_id,:post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comments.html.erb
<%@comments.each do|comment|%><br>
    <%=comment.post%>
    <%#= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' },
        :remote => true, :class => 'delete_pony' %>
<%end%>

app/views/articles/_popup.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
   
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
     
      <!-- Modal body -->
      <div class="modal-body">
       <div class="container">
   <div>    
   

      </div>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
     
    </div>
  </div>
</div>

</div>

app/views/articles/edit.html.erb
<center>
<h1>Update your post here</h1>
<%=form_for Article.new,url: article_path,method: :patch do |t|%>
    <%#=t.hidden_field :user_id,value: @user.id%>
    <%=t.label "Title"%><br>
	<%=t.text_field :title%><br><br>
	<%=t.label "Description"%><br>
	<%=t.text_field :description%><br><br>
	<%=t.label "Created_by"%><br>
	<%=t.text_field :created_by%><br><br>
	<%=t.label "Activate"%><br>
	<%=t.check_box :active%><br><br>
	<%=t.submit %>
	<%end%>
</center>

app/views/articles/index.html.erb
<center>
<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navbar bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%#=link_to "My Photos",post_path(id: current_user.id),class: "nav-link navbar-brand"%>
      </li>
      <li class="nav-item active">
        <%=link_to "Create Blog", new_article_path(id: current_user.id),class: "nav-link navbar-brand"%>
      </li>
       <li class="nav-item active">
       <%=button_to "Log out", destroy_user_session_path,method: :delete,class: "nav-link nav justify-content-end"%>
      </li>
      
      
    </ul>
   
  </div>
</nav>
  <h1>Articles</h1>

<table class="table">
  <thead>
    <tr>
      <center><th>Title</th></center>
      <center><th>Description</th></center>
      <th>Activate</th>
       <th>Actions</th>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
    
        <%if current_user.id == article.user_id %>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
          <%if article.active == true%>
            <td><%= link_to 'deactivate',active_articles_path(id:article.id), method: :post %>
              <%else%>
                <td><%= link_to 'activate',active_articles_path(id:article.id), method: :post %></td>
              <%end%>
        <td><%= link_to 'Show',article_path(id: article.id) %></td>
        <td><%= link_to 'Edit',edit_article_path(id: article.id) %></td>
        <td><%= link_to 'Destroy',article_path(id: article.id), method: :delete %></td>

        <td></td>
        
       <%elsif article.active == true%>

        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td></td>
        <td><%= link_to 'Show',article_path(id: article.id) %></td>
        <td></td>
        <td></td>
      </tr>
      <%end%>
    <% end %>
    <% #end %>
  </tbody>
</table>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<%end%>
</center>

app/views/articles/new.html.erb
<center>
<h1>Create your post here</h1>
<%=form_for Article.new,url: articles_path,method: :post do |t|%>
    
    <%=t.label "Title"%><br>
	<%=t.text_field :title%><br><br>
	<%=t.label "Description"%><br>
	<%=t.text_field :description%><br><br>
	<%=t.label "Created_by"%><br>
	<%=t.text_field :created_by%><br><br>
	<%=t.label "Activate"%><br>
	<%=t.check_box :active,{checked: false}%><br><br>
	<%=t.submit %>
	<%end%>
</center>

app/views/articles/show.html.erb
<h1>This is your post</h1>
Title-:<%=@article.title%><br>
Description-:<%=@article.description%><br>

<div>
                   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">New Comment</button>
                 </div>
                 <div id="comments">
                   <%= render "articles/comments"%>
                 </div><br>
                  </div>

           </div>
        </div>
     </div>
  </div>
</div>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Modal -->
<!-- <div class="modal fade" id="getCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" width=100px height=50px>
  <div class="modal-dialog modal-lg">
     <div class="modal-content">
      <div class="modal-header">
        <%#= form_for (@comment),:html => {:id => "form"} do |form| %>
          <div><%#= form.hidden_field :user_id, value:current_user.id%></div>
          <div><%#= form.hidden_field :article_id, value:@article.id%></div>
         
          <div class="field"><br>
            <%#= form.label :Comment %><br>
            <%#= form.text_field :post %>
          </div>
         
          <div class="actions",id="button"><br>
            <%#= form.submit%>
          </div>
        <%# end %>
      </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
     </div>
   </div>
  </div>
</div> -->

<!-- The Modal -->
 <div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
   
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
     
  
      <div class="modal-body">
       <div class="container">
   <div>    
   <%#= form_for (@comment),:html => {:id => "form"} do |form| %>
   <%= form_for (@comment), remote: true do |form| %>
     <div><%= form.hidden_field :user_id, value:current_user.id%></div>
     <div><%= form.hidden_field :article_id, value:@article.id%></div>
     
     <div class="field"><br>
       <%= form.label :Comment %><br>
       <%= form.text_field :post %>
     </div>
     
     <div class="actions",id="button"><br>
       <%= form.submit  %>
     </div>
   <% end %>

      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
     
     </div>
  </div>
</div>
 
 </div> 
<script type="text/javascript">
  $('form').submit(function(a) {
  a.preventDefault();
  
  var data = $('form').serialize();
  
  $.ajax({
     url: "/comments",
     type: 'POST',
     data: data ,
      success: function(data) {
        // debugger
        // location.reload(true);
        // debugger
         //data.find('input:text_field').val('').removeAttr('comment');
     
      }
   });
});
</script>

<script type="text/javascript">
  $("button").click(function(e){

   e.preventDefault() ;
   $.ajax({
     type: 'post',
     url: "/comments/popup",
     data: {},
      success: function(data) {
    
       <%#=render"blogs/popup"%>
       $("#getCodeModal").modal("toggle");
      }
   });
  });
</script>

<!-- <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">Add Comments</a>

<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Add Your Comment</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          <input type="text" id="defaultForm-email" class="form-control validate">
          <label data-error="wrong" data-success="right" for="defaultForm-email">Comment here</label>
        </div>

        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          <input type="password" id="defaultForm-pass" class="form-control validate">
          <label data-error="wrong" data-success="right" for="defaultForm-pass">Your password</label>
        </div> -->
<!-- 
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button class="btn btn-default">Post</button>
      </div>
    </div>
  </div>
</div>
 -->

app/views/comments/create.js.erb
$('#myModal').hide();
$('.modal-backdrop').hide();
$('#comments').html("<%= escape_javascript render(:partial => 'articles/comments', :locals => { :comments => @comments }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>